# Generated by Django 2.0.7 on 2019-07-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_auto_20190708_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='experince',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='price',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_deatils',
        ),
    ]
